/* ------------------------------------------------------------------
   loader.js — sets up the global TRIPS store and loads every data file.
   To add a NEW data file, add its path to the list below. To add a new
   place to an existing region, just edit that region's file in /data.
   ------------------------------------------------------------------ */
window.TRIPS = window.TRIPS || {
  places: [],     // every country / state / city / site we have a page for
  questions: [],  // hand-written quiz questions
  notes: [],      // journal entries
  trips: [],      // dated trips (mainly international)
  photos: {}      // placeId -> [{src, caption}]  (generated by tools/scan_photos.py)
};

(function () {
  var files = [
    'data/trips.js',
    'data/places-international.js',
    'data/places-karnataka.js',
    'data/places-tamilnadu.js',
    'data/places-kerala-ap-ts.js',
    'data/places-others.js',
    'data/places-more.js',
    'data/questions-international.js',
    'data/questions-karnataka.js',
    'data/questions-tamilnadu.js',
    'data/questions-kerala-ap-ts.js',
    'data/questions-others.js',
    'data/questions-more.js',
    'data/facts-international.js',
    'data/facts-karnataka.js',
    'data/facts-tamilnadu.js',
    'data/facts-kerala-ap-ts.js',
    'data/facts-others.js',
    'data/facts-more.js',
    'data/collections.js',
    'data/photos.js',
    'data/images.js'
  ];
  // document.write keeps the scripts synchronous and in order, which is what
  // we need for a no-build static site that must also work from file://
  for (var i = 0; i < files.length; i++) {
    document.write('<script src="' + files[i] + '"><\/script>');
  }
})();
