"""
build_maps.py — turns GeoJSON outlines into compact SVG path strings for the
cartoon locator maps on the place pages. Writes data/maps-svg.js.

    python tools/build_maps.py <world.geo.json> [india_states.geojson]

- World: equirectangular projection into a 1000 x 500 viewBox; every country
  becomes its own path (keyed by name) so the visited country can be highlighted.
- India: either the state file (each state a path, keyed by name) or, if none is
  given, India's outline taken from the world file. Projected into a 600 x 660
  viewBox covering lng 68–97.5 / lat 6–37.5.
Only place.html loads the output, so file size matters less than clarity.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "maps-svg.js"

WORLD_W, WORLD_H = 1000, 500
INDIA_BOX = (68.0, 97.5, 6.0, 37.5)      # lng min, lng max, lat min, lat max
INDIA_W = 600
INDIA_H = int(INDIA_W * (INDIA_BOX[3] - INDIA_BOX[2]) / (INDIA_BOX[1] - INDIA_BOX[0]) * 1.0)


def proj_world(lng, lat):
    return (lng + 180) / 360 * WORLD_W, (90 - lat) / 180 * WORLD_H


def proj_india(lng, lat):
    x = (lng - INDIA_BOX[0]) / (INDIA_BOX[1] - INDIA_BOX[0]) * INDIA_W
    y = (INDIA_BOX[3] - lat) / (INDIA_BOX[3] - INDIA_BOX[2]) * INDIA_H
    return x, y


def rings(geom):
    if geom["type"] == "Polygon":
        return geom["coordinates"]
    if geom["type"] == "MultiPolygon":
        return [r for poly in geom["coordinates"] for r in poly]
    return []


def to_path(geom, proj, decimals=1, min_points=4):
    parts = []
    for ring in rings(geom):
        pts, last = [], None
        for lng, lat in ring:
            x, y = proj(lng, lat)
            p = (round(x, decimals), round(y, decimals))
            if p != last:
                pts.append(p)
                last = p
        if len(pts) < min_points:
            continue
        parts.append("M" + " ".join(f"{x:g},{y:g}" for x, y in pts) + "Z")
    return "".join(parts)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    world = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    countries = {}
    india_geom = None
    for f in world["features"]:
        name = f["properties"].get("name") or f["properties"].get("NAME") or f.get("id")
        if name == "Antarctica":
            continue
        if name == "India":
            india_geom = f["geometry"]
        path = to_path(f["geometry"], proj_world)
        if path:
            countries[name] = path
    print(f"world: {len(countries)} countries")

    states = {}
    if len(sys.argv) > 2:
        ind = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
        for f in ind["features"]:
            props = f["properties"]
            name = props.get("NAME_1") or props.get("ST_NM") or props.get("st_nm") or props.get("name") or props.get("NAME")
            # the state file is very detailed: whole pixels are plenty at 600px wide
            path = to_path(f["geometry"], proj_india, decimals=0, min_points=6)
            if name and path:
                states[name] = states.get(name, "") + path
        print(f"india: {len(states)} states/UTs from {sys.argv[2]}")
    india_outline = to_path(india_geom, proj_india) if india_geom else ""

    js = (
        "/* AUTO-GENERATED by tools/build_maps.py — SVG outlines for the locator maps on place pages. */\n"
        f"TRIPS.mapWorld = {{ w: {WORLD_W}, h: {WORLD_H}, countries: {json.dumps(countries, ensure_ascii=False)} }};\n"
        f"TRIPS.mapIndia = {{ w: {INDIA_W}, h: {INDIA_H}, box: {list(INDIA_BOX)}, outline: {json.dumps(india_outline)}, states: {json.dumps(states, ensure_ascii=False)} }};\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
