"""
scan_photos.py — builds data/photos.js from the photos/ folder.

Usage (from the project root):
    python tools/scan_photos.py

How it works
- Every sub-folder of photos/ is a place id (e.g. photos/hampi/, photos/paris/).
  The id must match an `id` in data/places-*.js — the script warns if it doesn't.
- Every .jpg/.jpeg/.png/.webp/.gif inside is listed, sorted by name.
- Optional photos/<id>/captions.txt gives captions, one per line:
      IMG_2041.jpg | Sunrise from Matanga hill
  Files without a caption line get no caption.
- Nothing is copied or resized. Keep photos reasonably small (~1600px wide) so
  the site loads quickly on the phone — see tools/shrink_photos.py.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTOS = ROOT / "photos"
DATA = ROOT / "data"
OUT = DATA / "photos.js"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}


def known_place_ids():
    ids = set()
    for f in DATA.glob("places-*.js"):
        ids.update(re.findall(r"id:\s*'([a-z0-9\-]+)'", f.read_text(encoding="utf-8")))
    return ids


def read_captions(folder: Path):
    caps = {}
    cf = folder / "captions.txt"
    if cf.exists():
        for line in cf.read_text(encoding="utf-8").splitlines():
            if "|" in line:
                name, cap = line.split("|", 1)
                caps[name.strip().lower()] = cap.strip()
    return caps


def main():
    PHOTOS.mkdir(exist_ok=True)
    ids = known_place_ids()
    result = {}
    total = 0
    for folder in sorted(p for p in PHOTOS.iterdir() if p.is_dir()):
        pid = folder.name
        if pid not in ids:
            print(f"  ! photos/{pid}/ does not match any place id — skipped (check data/places-*.js)")
            continue
        caps = read_captions(folder)
        items = []
        for f in sorted(folder.iterdir()):
            if f.suffix.lower() in EXTS:
                rel = f"photos/{pid}/{f.name}"
                entry = {"src": rel}
                cap = caps.get(f.name.lower())
                if cap:
                    entry["caption"] = cap
                items.append(entry)
        if items:
            result[pid] = items
            total += len(items)
            print(f"  {pid}: {len(items)} photo(s)")

    body = json.dumps(result, indent=2, ensure_ascii=False)
    OUT.write_text(
        "/* AUTO-GENERATED by tools/scan_photos.py — do not edit by hand.\n"
        "   Drop photos into photos/<place-id>/ and run:  python tools/scan_photos.py\n"
        "   Optional captions: photos/<place-id>/captions.txt with lines \"filename | caption\" */\n"
        f"TRIPS.photos = {body};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {OUT.relative_to(ROOT)} — {total} photo(s) across {len(result)} place(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
